# Embedding

In [8]:
import torch
import torch.nn as nn

## Step-1 : build vocabulary

In [9]:
vocab = {
    "<PAD>": 0,
    "<UNK>": 1,
    "I": 2,
    "love": 3,
    "deep": 4,
    "learning": 5
}

## Step-2 : Sentence to Token Ids

In [10]:
token_ids = torch.tensor([2, 3, 4, 5])
print("Token IDs:")
print(token_ids)
print("Shape:", token_ids.shape)

Token IDs:
tensor([2, 3, 4, 5])
Shape: torch.Size([4])


## Step-3 : Embedding Layer

In [11]:
embedding=nn.Embedding(
    num_embeddings=len(vocab),
    embedding_dim=4
)
print("\nEmbedding Weight Matrix:")
print(embedding.weight)
print("Shape:", embedding.weight.shape)



Embedding Weight Matrix:
Parameter containing:
tensor([[-0.5049,  0.0926,  0.8826, -1.4165],
        [ 0.4776,  0.4653, -0.6256, -1.0725],
        [ 0.4886, -0.2720,  0.1925, -1.1911],
        [ 1.8613, -0.4789,  1.1306, -0.0266],
        [-1.4634, -1.7180,  0.7019,  1.6808],
        [-0.0763,  0.0916,  1.7493, -0.5955]], requires_grad=True)
Shape: torch.Size([6, 4])


## Step-4 : Embedded Lookup

In [12]:
embedded=embedding(token_ids)
print("\nEmbedded Lookup:")
print(embedded)
print("Shape:", embedded.shape)


Embedded Lookup:
tensor([[ 0.4886, -0.2720,  0.1925, -1.1911],
        [ 1.8613, -0.4789,  1.1306, -0.0266],
        [-1.4634, -1.7180,  0.7019,  1.6808],
        [-0.0763,  0.0916,  1.7493, -0.5955]], grad_fn=<EmbeddingBackward0>)
Shape: torch.Size([4, 4])


## Visulize All The Step together



```
Sentence
"I love deep learning"  --->**RAW TEXT**

                │
                ▼

["I","love","deep","learning"] ---> *Converting Into Token*

                │
                ▼

[2,3,4,5] -----> *Token IDS*

                │
                ▼

Embedding Layer (VocabSize X Embedding Dimesion)
Let's our vocab size 6
(6 × 4)

                │
                ▼
                *{LookUp Table}*

[
[-0.34,0.44,-0.90,1.23], --->Embedded I

[0.90,-1.12,0.54,0.22],  --->Embedded love

[-0.17,0.33,1.12,-0.48],--->Embedded deep

[0.75,-0.88,0.62,1.10] --->Embedded Learning
]

Shape = (4,4)

                │
                ▼

Next

Generate

Q

K

V
```





---



---


Z.I. Turjo

---
---

