#LayerNormalization

In [1]:
import torch
import torch.nn as nn

In [2]:
class MyLayerNorm(nn.Module):
  def __init__(self,d_model,eps=1e-5):
    super().__init__()

    self.gamma=nn.Parameter(torch.ones(d_model))
    self.beta=nn.Parameter(torch.zeros(d_model))
    self.eps=eps

  def forward(self,x):
    print("="*50)
    print("Input")
    print(x)
    print("Input Shape:",x.shape)

    mean=x.mean(dim=-1,keepdim=True)
    print("="*50)
    print("\nMean")
    print(mean)
    print("Mean Shape:",mean.shape)

    var=x.var(dim=-1,keepdim=True)
    print("="*50)
    print("\nVariance")
    print(var)
    print("Variance Shape:",var.shape)

    x_hat=(x-mean)/torch.sqrt(var+self.eps)
    print("="*50)
    print("\nNormalized Input")
    print(x_hat)
    print("\nX_hat Shape",x_hat.shape)

    out=self.gamma*x_hat+self.beta
    print("="*50)
    print("\nOutput")
    print(out)
    print("Output Shape:",out.shape)

    return out

In [3]:
x=torch.tensor([
    [
        [1.,2.,3.,4.],
        [5.,6.,7.,8.]
    ]
]) ##(1,2,4)(batch=1,seq_len=2,embed_dim=4)

layer=MyLayerNorm(d_model=4)
output=layer(x)

Input
tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.]]])
Input Shape: torch.Size([1, 2, 4])

Mean
tensor([[[2.5000],
         [6.5000]]])
Mean Shape: torch.Size([1, 2, 1])

Variance
tensor([[[1.6667],
         [1.6667]]])
Variance Shape: torch.Size([1, 2, 1])

Normalized Input
tensor([[[-1.1619, -0.3873,  0.3873,  1.1619],
         [-1.1619, -0.3873,  0.3873,  1.1619]]])

X_hat Shape torch.Size([1, 2, 4])

Output
tensor([[[-1.1619, -0.3873,  0.3873,  1.1619],
         [-1.1619, -0.3873,  0.3873,  1.1619]]], grad_fn=<AddBackward0>)
Output Shape: torch.Size([1, 2, 4])


## Shape Summary



```
| Variable | Shape   |
| -------- | ------- |
| Input x  | (B,S,D) |
| Mean     | (B,S,1) |
| Variance | (B,S,1) |
| x_hat    | (B,S,D) |
| Gamma    | (D,)    |
| Beta     | (D,)    |
| Output   | (B,S,D) |

```

